image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - npm run generate
  artifacts:
    paths:
      - public
  only:
    - master
